#' Plot MCMC Trace for Robust LPA Models
#'
#' Draws multi-chain trace plots for the MCMC engine of
#' \code{\link{robust_lpa}} using \pkg{bayesplot}. By default, the profile
#' means, profile variances (the diagonal of each covariance matrix), and
#' mixing proportions are shown; use \code{pars} to select a subset.
#'
#' @details
#' \code{robust_mcmc_cpp} (called internally by \code{robust_lpa(engine =
#' "MCMC")}, once per chain) returns its draws as a nested list
#' (\code{mu_chain}, \code{sigma_chain}, \code{pi_chain}), not the
#' array/matrix format \code{bayesplot::mcmc_trace()} expects. This function
#' reshapes the raw per-chain draws stored in \code{model$mcmc_draws$chains}
#' into an \code{[iterations, chains, parameters]} array before calling
#' \code{bayesplot::mcmc_trace()}, so every chain is shown overlaid as a
#' separate colored trace -- the standard visual convergence check
#' (well-mixed, overlapping chains suggest convergence; chains that stay
#' visually separated suggest they have not converged, consistent with a
#' high Gelman-Rubin \eqn{\hat{R}}; see \code{model$mcmc_diagnostics}).
#'
#' Parameter names follow the pattern \code{"mu[g,j]"} (mean of variable
#' \code{j} in profile \code{g}), \code{"sigma[g,j]"} (variance of variable
#' \code{j} in profile \code{g}), and \code{"pi[g]"} (mixing proportion of
#' profile \code{g}). Off-diagonal covariance terms are not included by
#' default to keep the default plot readable; inspect
#' \code{model$mcmc_draws$chains[[1]]$sigma_chain} directly if you need those.
#'
#' @param model A fitted model object returned by \code{\link{robust_lpa}} with \code{engine = "MCMC"}.
#' @param pars Optional character vector of parameter names to visualize (a
#'   subset of the default \code{"mu[...]"} / \code{"sigma[...]"} / \code{"pi[...]"}
#'   names described in Details). Default \code{NULL} plots all of them.
#' @return A ggplot object generated by \code{bayesplot::mcmc_trace()}.
#' @examples
#' \donttest{
#' data(neuro_data)
#' x <- scale(as.matrix(neuro_data[, c("Memory", "RT_Stroop")]))
#' fit <- suppressWarnings(robust_lpa(x, G = 2, model = 2, engine = "MCMC",
#'                                     mcmc_iter = 200, n_chains = 2))
#' summary(fit)  # profile means and MCMC convergence diagnostics
#' plot_mcmc_chains(fit)
#' }
#' @export
plot_mcmc_chains <- function(model, pars = NULL) {

  if (is.null(model$engine) || model$engine != "MCMC") {
    stop("Traceplots are only available for models estimated with the MCMC engine.")
  }

  if (!requireNamespace("bayesplot", quietly = TRUE)) {
    stop("The 'bayesplot' package is required for this function. Install it with install.packages('bayesplot').")
  }
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop("The 'ggplot2' package is required for this function. Install it with install.packages('ggplot2').")
  }

  draws <- model$mcmc_draws
  if (is.null(draws) || is.null(draws$chains)) {
    stop("The model does not contain MCMC draws. Ensure the algorithm is saving the chains.")
  }

  draws_array <- .reshape_mcmc_draws(draws$chains)
  n_chains <- dim(draws_array)[2]

  if (!is.null(pars)) {
    unknown <- setdiff(pars, dimnames(draws_array)[[3]])
    if (length(unknown) > 0) {
      stop("Unknown parameter name(s): ", paste(unknown, collapse = ", "),
           ". Available parameters: ", paste(dimnames(draws_array)[[3]], collapse = ", "))
    }
  }

  # bayesplot::mcmc_trace()'s own default for `pars` is character(0) (meaning
  # "no explicit selection, show every parameter"), NOT NULL -- passing NULL
  # through reaches its internal select_parameters(), which requires
  # is.character(explicit) and errors on NULL ("is.character(explicit) is
  # not TRUE"). Translate our own NULL default (documented above as "plot
  # all of them") into bayesplot's own character(0) default.
  bayesplot_pars <- if (is.null(pars)) character(0) else pars

  p <- bayesplot::mcmc_trace(draws_array, pars = bayesplot_pars) +
    ggplot2::theme_minimal() +
    ggplot2::labs(
      title = "MCMC Traceplots",
      subtitle = sprintf(
        "%d chain%s shown (see model$mcmc_diagnostics for Gelman-Rubin R-hat / ESS)",
        n_chains, if (n_chains == 1) "" else "s"
      )
    )

  return(p)
}

#' Parameter Names for the Flattened MCMC Parameter Vector
#'
#' Builds the \code{"mu[g,j]"} / \code{"sigma[g,j]"} / \code{"pi[g]"}
#' parameter-name vector shared by \code{\link{plot_mcmc_chains}} and the
#' internal MCMC convergence-diagnostics helper
#' (\code{.compute_mcmc_diagnostics}), so both stay in the exact same
#' parameter order as \code{.mcmc_iter_to_vector}.
#'
#' @param G Integer, the number of latent profiles.
#' @param p Integer, the number of variables.
#' @return A character vector of length \code{G*p + G*p + G} (g varying
#'   slowest, j fastest within the \code{mu}/\code{sigma} blocks).
#' @keywords internal
#' @noRd
.mcmc_param_names <- function(G, p) {
  mu_names <- sprintf("mu[%d,%d]", rep(1:G, each = p), rep(1:p, times = G))
  sigma_names <- sprintf("sigma[%d,%d]", rep(1:G, each = p), rep(1:p, times = G))
  pi_names <- sprintf("pi[%d]", 1:G)
  c(mu_names, sigma_names, pi_names)
}

#' Flatten a Single MCMC Iteration into a Numeric Parameter Vector
#'
#' Converts one iteration's raw \code{mu_chain[[iter]]} /
#' \code{sigma_chain[[iter]]} / \code{pi_chain[iter, ]} values (as returned
#' by \code{robust_mcmc_cpp()}) into a single numeric vector, in the same
#' order as \code{\link{.mcmc_param_names}}.
#'
#' @param mu_iter The \code{mu_chain[[iter]]} element (a list of \code{G} mean vectors).
#' @param sigma_iter The \code{sigma_chain[[iter]]} element (a list of \code{G} covariance matrices).
#' @param pi_iter A numeric vector of length \code{G}, the \code{pi_chain[iter, ]} row.
#' @param G Integer, the number of latent profiles.
#' @param p Integer, the number of variables.
#' @return A numeric vector of length \code{G*p + G*p + G}.
#' @keywords internal
#' @noRd
.mcmc_iter_to_vector <- function(mu_iter, sigma_iter, pi_iter, G, p) {
  mu_vals <- numeric(0)
  sigma_vals <- numeric(0)
  # NOTE: g varies slowest, j fastest, to exactly match .mcmc_param_names()
  # (rep(..., each = p) / rep(..., times = G)) -- the two must be kept in
  # sync by hand, since a mismatch would silently mislabel every parameter
  # except mu[1,1]/sigma[1,1].
  for (g in 1:G) {
    mu_vals <- c(mu_vals, as.numeric(mu_iter[[g]]))
    sigma_vals <- c(sigma_vals, diag(sigma_iter[[g]]))
  }
  c(mu_vals, sigma_vals, as.numeric(pi_iter))
}

#' Reshape Raw Multi-Chain MCMC Draws into a bayesplot-Compatible Array
#'
#' Converts the per-chain list output of \code{robust_mcmc_cpp()} (each
#' element with \code{mu_chain}, \code{sigma_chain}, and \code{pi_chain}, as
#' stored in \code{model$mcmc_draws$chains}) into an
#' \code{[iterations, chains, parameters]} numeric array with named
#' dimensions, as required by \code{bayesplot::mcmc_trace()} and by the
#' internal MCMC convergence-diagnostics helper (\code{.compute_mcmc_diagnostics}).
#'
#' @param chains A list of length \code{n_chains}, each element as returned
#'   by \code{robust_mcmc_cpp()} (i.e. with \code{mu_chain}, \code{sigma_chain},
#'   \code{pi_chain}).
#' @param iters Optional integer vector of iteration indices to keep (e.g. to
#'   drop burn-in before computing convergence diagnostics). Default
#'   \code{NULL} keeps every iteration (used for trace plots, where the
#'   burn-in period is itself informative to look at).
#' @return A numeric array of dimension \code{[length(iters), n_chains, G*p + G*p + G]}
#'   with dimnames \code{list(NULL, "chain:<k>", <parameter names>)}.
#' @keywords internal
#' @noRd
.reshape_mcmc_draws <- function(chains, iters = NULL) {
  n_chains <- length(chains)
  mcmc_iter <- length(chains[[1]]$mu_chain)
  G <- length(chains[[1]]$mu_chain[[1]])
  p <- length(chains[[1]]$mu_chain[[1]][[1]])

  if (is.null(iters)) iters <- seq_len(mcmc_iter)
  n_iters <- length(iters)

  param_names <- .mcmc_param_names(G, p)
  n_params <- length(param_names)

  draws_array <- array(NA_real_, dim = c(n_iters, n_chains, n_params))

  for (chain_id in seq_len(n_chains)) {
    ch <- chains[[chain_id]]
    for (i in seq_along(iters)) {
      iter <- iters[i]
      draws_array[i, chain_id, ] <- .mcmc_iter_to_vector(
        ch$mu_chain[[iter]], ch$sigma_chain[[iter]], ch$pi_chain[iter, ], G, p
      )
    }
  }

  dimnames(draws_array) <- list(NULL, paste0("chain:", seq_len(n_chains)), param_names)

  draws_array
}
