# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gmm_class_estep_cpp <- function(y, time, outc, starts, beta, D, sig2, K, degree, nrand, dist, nu) {
    .Call(`_RobustLPA_gmm_class_estep_cpp`, y, time, outc, starts, beta, D, sig2, K, degree, nrand, dist, nu)
}

gmm_class_suffstats_cpp <- function(y, time, outc, starts, beta, D, sig2, K, degree, nrand, z, w, t_scatter) {
    .Call(`_RobustLPA_gmm_class_suffstats_cpp`, y, time, outc, starts, beta, D, sig2, K, degree, nrand, z, w, t_scatter)
}

gmm_class_gls_cpp <- function(y, time, outc, starts, D, sig2, K, degree, nrand, z, w) {
    .Call(`_RobustLPA_gmm_class_gls_cpp`, y, time, outc, starts, D, sig2, K, degree, nrand, z, w)
}

gmm_class_resid_cpp <- function(y, time, outc, starts, beta, bhat, zcz, K, degree, nrand, z, w, t_scatter) {
    .Call(`_RobustLPA_gmm_class_resid_cpp`, y, time, outc, starts, beta, bhat, zcz, K, degree, nrand, z, w, t_scatter)
}

gmm_mcmc_chain_cpp <- function(y, time, outc, starts, K, degree, nrand, G, mcmc_iter, robust_type, alpha, nu_init, estimate_nu, re_equal, resid_equal, re_structure, rate_growth, rate_diff, rate_group, group_scale, group_diff, beta_prior_sd, re_prior_scale, beta0, D0, sig2_0, pi0) {
    .Call(`_RobustLPA_gmm_mcmc_chain_cpp`, y, time, outc, starts, K, degree, nrand, G, mcmc_iter, robust_type, alpha, nu_init, estimate_nu, re_equal, resid_equal, re_structure, rate_growth, rate_diff, rate_group, group_scale, group_diff, beta_prior_sd, re_prior_scale, beta0, D0, sig2_0, pi0)
}

robust_mean_cpp <- function(X, threshold) {
    .Call(`_RobustLPA_robust_mean_cpp`, X, threshold)
}

class_estep_cpp <- function(X, mu, Sigma, pat_obs, pat_rows, dist, nu) {
    .Call(`_RobustLPA_class_estep_cpp`, X, mu, Sigma, pat_obs, pat_rows, dist, nu)
}

class_mstep_cpp <- function(X, z, w, mu_cur, Sigma_cur, pat_obs, pat_rows, lambda, t_scatter) {
    .Call(`_RobustLPA_class_mstep_cpp`, X, z, w, mu_cur, Sigma_cur, pat_obs, pat_rows, lambda, t_scatter)
}

pairwise_moments_cpp <- function(X, z) {
    .Call(`_RobustLPA_pairwise_moments_cpp`, X, z)
}

solve_lsap_cpp <- function(cost) {
    .Call(`_RobustLPA_solve_lsap_cpp`, cost)
}

mcmc_chain_cpp <- function(X, G, model, mcmc_iter, prior_laplace, robust_type, alpha, nu_init, estimate_nu, init_mu, init_sigma, init_pi, pat_obs, pat_rows) {
    .Call(`_RobustLPA_mcmc_chain_cpp`, X, G, model, mcmc_iter, prior_laplace, robust_type, alpha, nu_init, estimate_nu, init_mu, init_sigma, init_pi, pat_obs, pat_rows)
}

